apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: agtechengineers-com-tls
spec:
  secretName: agtechengineers
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: agtechengineers.com
  dnsNames:
    - agtechengineers.com
    - www.agtechengineers.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - agtechengineers.com
          - www.agtechengineers.com
